### ISSUE TITLE
Official Frontier T16000MHOTAS bindings show "invalid" for holo me controls

### ISSUE THREAD

**Issue by freiheit** [richardbuckle/EDRefCard#32]
On my system, the file "T16000MHOTAS.binds" in Program Files (x86)\Steam\steamapps\common\Elite Dangerous\Products\elite-dangerous-64\ControlSchemes shows two "invalid" items under HoloMe when I upload it to edrefcard.

```
	<CommanderCreator_Undo>
		<Primary Device="Keyboard" key="Key_Z"/>
		<Secondary Device="{NoDevice}" key=""/>
	</CommanderCreator_Undo>
	<CommanderCreator_Redo>
		<Primary Device="Keyboard" key="Key_X"/>
		<Secondary Device="{NoDevice}" key=""/>
	</CommanderCreator_Redo>
```

Looks like maybe the default bindings file doesn't have a space between `"` and `/` and that's what edrefcard doesn't like?

**Comment by richardbuckle** [comment]
Thanks for the report!

It's because the `key` in `key=` is in lower case. It should be `Key=`. If you see an invalid item, it is usually either that or the value having the wrong case such as `Key_z`.

[The XML spec](https://www.w3.org/TR/xml/#sec-terminology) is very explicit that matching must be case-sensitive, and the XML parser that I use respects that. The in-game controls editor always emits correctly-cased XML, but it in several cases FDev have hand-edited their defaults, cocked it up, and instead of fixing the bindings file they have masked their errors by having the game be more forgiving about parsing than the XML spec permits.

If you look at line 389 of your bindings you will see that it is bound to `Joy_VAxis`. Fun fact: the throttle has no such axis. It should be `Joy_UAxis`. This is how I know that they have been hand-editing their bindings.

The really galling thing is that I raised a bug report on all these way back, and even supplied a zip file with everything fixed for them. It got completely ignored, of course.

Before you ask, yes I could in theory distort my code to be as sloppy as theirs in what it accepts, but I refuse to do so.

**Comment by richardbuckle** [comment]
#30 is related.
