### ISSUE TITLE
Match modifier colors with Xbox controller colors?

### ISSUE THREAD

**Issue by klausw** [richardbuckle/EDRefCard#78]
This is a somewhat minor issue, but I was trying to print the default controller layout to help some new players, and it's a bit confusing that the modifier colors use a color scheme that roughly matches the Xbox face button colors, but in a mixed-up order:

![image](https://github.com/richardbuckle/EDRefCard/assets/1392351/103ff8f6-0ad4-416a-a7a9-d1ab47bacf46)

| Modifier | Current color | Xbox button | Xbox color |
|-----------|---------------|---------------|-------------|
| 1 | red | B | red |
| 2 | green | Y | yellow |
| 3 | purple | A | green |
| 4 | orange | X | blue |

Would it be possible to tweak this to get the colors to match? That would help make the information more glanceable for new players. For example, if the mapping from modifier numbers to colors should stay the same, maybe use a new modifier ordering? B=1, A=2, X=3, Y=4 would work I think.

Here's a crude attempt at swapping the colors using an image editor:

![elite-dangerous-controller-mapping](https://github.com/richardbuckle/EDRefCard/assets/1392351/de85807c-a32b-4d95-ba16-cb823545eb9f)

**Comment by klausw** [comment]
Thank you!

**Comment by richardbuckle** [comment]
To clarify, this issue was closed because I have handed the site over to new maintainers who wish to start clean with a new repo.

If this issue is still important to you, I would encourage you to open an issue with them. Their repo is https://github.com/brammmers/edrefcard2 and the forum thread is [here](https://forums.frontier.co.uk/threads/edrefcard-v1-4-new-hosting-new-maintainers-the-follow-on-to-edrefcard-makes-a-printable-reference-card-of-your-controller-bindings.627609/).
